### ISSUE TITLE
speaker notes does not work

### ISSUE THREAD

**Issue by hholst80** [webpro/reveal-md#111] opened 2017-05-07 20:05 UTC
# Input file

```
# A small presentation

* I want to talk about math:

$$
F(x) = \int_a^x f(s) \mathrm{d}s
$$

Note: This stuff is fundamental.


---

# An empty slide.

* Except for the title.
* And this bullet list.
```

```
Unhandled rejection TypeError: path must be a string or Buffer
    at fs.readFile (fs.js:297:11)
    at go$readFile (/data/node_modules/graceful-fs/graceful-fs.js:73:14)
    at Object.readFile (/data/node_modules/graceful-fs/graceful-fs.js:70:12)
    at Object.tryCatcher (/data/node_modules/bluebird/js/release/util.js:16:23)
    at Object.ret [as readFileAsync] (eval at makeNodePromisifiedEval (/data/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
    at renderMarkdownAsSlides (/data/node_modules/reveal-md/lib/render.js:59:10)
    at Layer.handle [as handle_request] (/data/node_modules/express/lib/router/layer.js:95:5)
    at next (/data/node_modules/express/lib/router/route.js:131:13)
    at updatePathOptions (/data/node_modules/reveal-md/lib/serve.js:19:3)
    at Layer.handle [as handle_request] (/data/node_modules/express/lib/router/layer.js:95:5)
    at next (/data/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/data/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/data/node_modules/express/lib/router/layer.js:95:5)
    at /data/node_modules/express/lib/router/index.js:277:22
    at param (/data/node_modules/express/lib/router/index.js:349:14)
    at param (/data/node_modules/express/lib/router/index.js:365:14)

Unhandled rejection TypeError: path must be a string or Buffer
    at fs.readFile (fs.js:297:11)
    at go$readFile (/data/node_modules/graceful-fs/graceful-fs.js:73:14)
    at Object.readFile (/data/node_modules/graceful-fs/graceful-fs.js:70:12)
    at Object.tryCatcher (/data/node_modules/bluebird/js/release/util.js:16:23)
    at Object.ret [as readFileAsync] (eval at makeNodePromisifiedEval (/data/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
    at renderMarkdownAsSlides (/data/node_modules/reveal-md/lib/render.js:59:10)
    at Layer.handle [as handle_request] (/data/node_modules/express/lib/router/layer.js:95:5)
    at next (/data/node_modules/express/lib/router/route.js:131:13)
    at updatePathOptions (/data/node_modules/reveal-md/lib/serve.js:19:3)
    at Layer.handle [as handle_request] (/data/node_modules/express/lib/router/layer.js:95:5)
    at next (/data/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/data/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/data/node_modules/express/lib/router/layer.js:95:5)
    at /data/node_modules/express/lib/router/index.js:277:22
    at param (/data/node_modules/express/lib/router/index.js:349:14)
    at param (/data/node_modules/express/lib/router/index.js:365:14)

```

PS. reveal-md is getting devilishly popular! ;-)

![image](https://cloud.githubusercontent.com/assets/6200749/25784623/d9e8bc12-3370-11e7-9971-8631be46a17b.png)

**Comment by davidka** [comment] 2017-05-08 08:54
The notes do not work for me when I start with a parent folder.With a certain slide it works

**Comment by webpro** [comment] 2017-05-09 08:34
If anybody feels like debugging this, that would be great.

**Comment by webpro** [comment] 2017-05-09 19:12
The provided markdown works fine for me, in any (sub) directory. Speakers notes visible after pressing "s". I'm going to close this issue until someone provides a reproducible test case.

**Closed by webpro** 2017-05-09 19:12 UTC
Labels: bug

**Comment by paddelkraft** [comment] 2017-05-11 11:45
i actually have the same problem on both my mac and my pc. What happens is that if i start  reveal-md like this `reveal-md` the `options.relativePath` is undefind  and throws the exception but if reveal-md is started with the reference to a specific file `reveal-md ptesentation.md` it works

**Comment by paddelkraft** [comment] 2017-05-11 20:02
@webpro 
The problem is that `parsePath` is called with a query string 
`pathArg="/demo/a.md?receiver&progress=false&history=false&transition=none&autoSlide=0&backgroundTransition=none&controls=false"
 when speaker notes is opened and `parsePath`cant find a file by that name it returns undefined

changing line 33 in `options.js parsePath`  into  
 `const filePath = path.join(baseDir || process.cwd(), pathArg.split("?")[0]);`   
to remove the query string (if there is any) fixes the problem
