### ISSUE TITLE
Problem accessing static files e.g. images

### ISSUE THREAD

**Issue by jeud** [webpro/reveal-md#136] opened 2017-09-01 13:14 UTC
Dear all

I like to access some static files e.g. images from within the markdown file as `![](/images/image1.png)` but it was not able to access I also tried to open the browser with this URL `http://localhost:0000/images/image1.png`, it also could not be accessed

P.S. It used to work with some older version of `reveal-md`

Please guide
Thanks

*File Structure*
```
+-images
    |-image1.png
    |-image2.png
|-slide1.md
|-slide2.md
```

> `reveal-md` version: 0.4.1

**Comment by webpro** [comment] 2017-09-04 19:08
You should use relative links (ie. `images/image1.png`).

**Comment by japgolly** [comment] 2017-09-07 01:26
I'm having the same issue. This doesn't work even with relative links.

**Comment by japgolly** [comment] 2017-09-07 01:29
Hmm, prepending `assets/` makes it work, even though that directory doesn't exist locally.

**Comment by webpro** [comment] 2017-09-07 15:01
Duplicate of #116. Let's discuss over there.

**Closed by webpro** 2017-09-07 15:01 UTC
