### ISSUE TITLE
?print-pdf option not working

### ISSUE THREAD

**Issue by breschke** [webpro/reveal-md#139] opened 2017-09-13 16:52 UTC
Trying to use reveal-md as a full replacement for course lecture presentations and notes. The ability to print to pdf version of slides is crucial for me. Neither the `--print file.pdf` option (see #117) nor the ?print-pdf option are working. I've closely followed the instructions in #125 @wwoods; the result is one slide only, and when I attempt to print using the Chrome print dialog, the one slide is not formatted as expected (see screen shots).

```
> node -v
v8.4.0
> reveal-md --version
0.4.1
> phantomjs --version
2.1.1
```

Chrome Version 60.0.3112.113 (Official Build) (64-bit)

Mac OS 10.12.6

![screenshot 2017-09-13 10 47 47](https://user-images.githubusercontent.com/4975604/30389810-2c453eda-9871-11e7-8519-4bf293164c4b.png)

![screenshot 2017-09-13 10 49 35](https://user-images.githubusercontent.com/4975604/30389836-403870e2-9871-11e7-8d11-3ab356fb5125.png)

**Comment by webpro** [comment] 2017-09-13 19:21
Hi @breschke, this is a know issue (as you've pointed out), so I'm going to close this one. I know it can be frustrating that this isn't working properly, but I don't have the time nor a personal interest in fixing this. However, I think your report and screenshots are helpful for understanding the issue to anyone interested.

**Comment by webpro** [comment] 2017-09-13 19:22
Dup of #117.

**Closed by webpro** 2017-09-13 19:21 UTC

**Comment by breschke** [comment] 2017-09-13 20:04
Actually, I don't think the problem with the Chrome-based printing functionality (?pdf-print) is known. This is distinct from the `--print file.pdf` option. So, it is not a duplication of #117. Kindly re-open so that we can work on either printing option.

**Comment by breschke** [comment] 2017-09-13 20:07
@gmatht mentioned last week that there doesn't seem to be an issue for ?print-pdf specifically. I'm trying to open one.

**Comment by wwoods** [comment] 2017-09-13 20:15
@breschke  Two things:

1. Did you check the "Background Graphics" checkbox in the chrome print dialog?

2. I also mentioned using the following CSS for slide centering:

    .reveal .slides section {
        display: flex !important;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }

  If you haven't yet tried adding that, please do, as that was needed for mine to work.  Also, just for the record, I now use the rst2html5 Python tool for making my lecture slides.  Added  bonus, it produces a single-file HTML that I can just upload and have students access directly (or, of course, I can ?print-pdf it).

**Comment by breschke** [comment] 2017-09-13 20:23
@wwoods Thanks--I had tried checking "Background Graphics": no effect. The CSS has centered the slides, as seen below, but still only one slide is printed. Is it expected to change to a black-and-white theme (different than the original)?

![screenshot 2017-09-13 14 19 49](https://user-images.githubusercontent.com/4975604/30398814-f6f665ce-988e-11e7-9e3e-e8cda2389686.png)

**Comment by breschke** [comment] 2017-09-13 20:39
I can replicate the problem with a minimal example:

`tmp.md`:

```
---
title: Test Deck
css: ./css/custom.css
---

# Testing

---

# 123
```

where  `./css/custom.css` is:

```
.reveal .slides section {
    display: flex !important;
    flex-direction: column;
    align-items: center;
    justify-content: center;
}
```

and server command is:

``` > 
reveal-md tmp.md 
```

Result doesn't print slide 2 (containing 123) and prints slide 1 as black text on white.

![screenshot 2017-09-13 14 36 25](https://user-images.githubusercontent.com/4975604/30399525-38cadc3a-9891-11e7-9835-8c994ade3acb.png)

**Comment by wwoods** [comment] 2017-09-13 22:16
That's weird, unfortunately I'm not sure why only one page would be printing.  When I do it, I can't scroll to the other slides, but they are there (and show up correctly in Chrome's print preview).  

Can you post your whole CSS theme?  I'd suspect the issue is there.  For instance, with background graphics, your slide theming must be on the "body" element and not on the ".slide" element.

**Comment by gmatht** [comment] 2017-09-14 01:43
Note that printing only the first page is a common problem with reveal.js.

I managed to get Chrome to print all the pages by exporting to a static website, (`reveal-md slides.md --static`), then opening `_static/index.html` and replacing the line

    <link rel="stylesheet" href="./css/print/paper.css" type="text/css" media="print">

with 

    <script>
            var link = document.createElement( 'link' );
            link.rel = 'stylesheet';
            link.type = 'text/css';
            link.href = window.location.search.match( /print-pdf/gi ) ? 'css/print/pdf.css' : 'css/print/paper.css';
            document.getElementsByTagName( 'head' )[0].appendChild( link );
    </script>

**Comment by breschke** [comment] 2017-09-18 15:41
@wwoods I use the default theme/CSS in my minimal example and still have the one-page problem.

@gmatht, printing the static website may be on the right track: I am able to print multiple pages of my slides this way, but they don't appear to be formatted as slides (e.g., pages don't break after slides). I followed your suggestion and edited `index.html`, but unfortunately this doesn't seem to make any change to resulting print-out.

**Comment by jinwoo** [comment] 2017-10-22 22:38
I have a PR for fixing this: #144
