### ISSUE TITLE
pdf print is generating an extra blank page

### ISSUE THREAD

**Issue by dantrevino** [webpro/reveal-md#146] opened 2017-11-15 17:11 UTC
slides: https://raw.githubusercontent.com/dantrevino/blockstack-portland/master/2017-11-13-Nike-PES-COP-Engineering/slides.md

resulting pdf: https://github.com/dantrevino/blockstack-portland/blob/master/2017-11-13-Nike-PES-COP-Engineering/blockstack.pdf

```bash
which phantomjs
/usr/local/bin/phantomjs

reveal-md --version
0.5.0
```

**Comment by webpro** [comment] 2017-11-15 17:45
Guess the blank pages are caused by the `<section>` tags. They are not closed. You should try to either wrap the whole slide in a section, or make it a self-closing tag.

**Comment by dantrevino** [comment] 2017-11-15 18:49
Hmmm...Neither seems to help.  I'm running this on Mac currently. 

wrapping section tag

> slides.md: https://raw.githubusercontent.com/dantrevino/blockstack-portland/d8cb748be8219c83805e092779b2f34465424a51/2017-11-13-Nike-PES-COP-Engineering/slides.md
> 
> resulting pdf: https://github.com/dantrevino/blockstack-portland/blob/d8cb748be8219c83805e092779b2f34465424a51/2017-11-13-Nike-PES-COP-Engineering/blockstack.pdf

self-closing section tag

> slides.md: https://raw.githubusercontent.com/dantrevino/blockstack-portland/self-closing/2017-11-13-Nike-PES-COP-Engineering/slides.md
> 
> resulting pdf: https://github.com/dantrevino/blockstack-portland/blob/self-closing/2017-11-13-Nike-PES-COP-Engineering/blockstack-self-closing.pdf

**Comment by webpro** [comment] 2017-11-16 10:04
It looks like you are setting a background color. You can also use CSS for this (https://github.com/webpro/reveal-md#custom-css).

**Comment by webpro** [comment] 2017-12-09 17:03
Closing due to inactivity.

**Closed by webpro** 2017-12-09 17:03 UTC
