### ISSUE TITLE
async SyntaxError

### ISSUE THREAD

**Issue by caopeirui** [webpro/reveal-md#365] opened 2021-04-05 15:13 UTC
My environment is
```
macOS 10.14.5
node v6.10.0
npm 6.13.1
```
The error is
```
 ~/Downloads » reveal-md mytest.md                                                                            cpr@cprdeMacBook-Pro
/usr/local/lib/node_modules/reveal-md/bin/reveal-md.js:29
(async () => {
       ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```
How should I do?

**Comment by webpro** [comment] 2021-04-05 18:47
Duplicate of #264. See https://github.com/webpro/reveal-md/issues/264#issuecomment-813570753

**Closed by webpro** 2021-04-05 18:47 UTC

**Comment by caopeirui** [comment] 2021-04-06 01:04
@webpro Thank you very much. 
I really appreciate your prompt reply. The problem has been solved.
