### ISSUE TITLE
Background image for single slide?

### ISSUE THREAD

**Issue by DanielJonesEB** [webpro/reveal-md#49] opened 2015-11-13 16:06 UTC
How do I set the background for an individual slide? I've tried using HTML within a .md document, but that seems to end up with nested `slide` tags in the rendered HTML, and no background image is visible. Any ideas?

```

> Some quote

---

<section data-background=”image.jpg”>
  <h2>Subtle subtext</h2>
</section>

---

rest of presentation

```

**Comment by webpro** [comment] 2015-11-15 19:10
I think the issue is that `---` creates a slide (`<section>` tag), and then the nested slide `<section data-background>` is not parsed by reveal.js. So I'm afraid it's not possible to do it this way.It would require some new custom syntax in reveal-md to get such attributes in the created slide(s).

**Comment by bmcminn** [comment] 2015-11-17 02:54
I think having the slide generator create a unique ID for the slide would allow you to use a CSS `background-image` to potentially solve this.

**Comment by webpro** [comment] 2015-11-21 12:14
Thanks @bmcminn, that's a good idea.

@EngineerBetter would that help? I.e. each slide would get a named `id` attribute taken from e.g. `Slide: slide-name` annotation in the Markdown.

**Comment by gabrielem** [comment] 2016-01-14 17:21
@webpro yes it is a good way to sovle the problem, I'm just thinking... when it will be available? :)

**Comment by webpro** [comment] 2016-01-17 20:55
My solution wouldn't be hard, it would require a PR in reveal.js, in the [Markdown plugin](https://github.com/hakimel/reveal.js/blob/master/plugin/markdown/markdown.js). If anybody's up to it, I'd be happy to update to a new version of reveal.js.

Another option is to use a custom theme with reveal-md, and then use something CSS like `:nth-child(n)` to apply background to individual slides.

**Comment by extropianer** [comment] 2016-01-23 18:12
@EngineerBetter did you try using the [slide attributes](https://github.com/hakimel/reveal.js#markdown)?
For me using a `<!-- .slide: data-background="./image1.png" -->` after the slide separator adds a background image.
Came across that feature when I was going to do a PR for custom IDs. Looks like it's not necessary though :)
This way you can also add `id="slidename"` tags to a specific slide.

**Comment by bmcminn** [comment] 2016-01-24 00:49
@extropianer Good find :) May be able to close this afterall :P

**Comment by grigio** [comment] 2016-03-11 10:30
@anoff Thanks!
Maybe these tricks should be mentioned in the docs

**Comment by webpro** [comment] 2016-03-23 12:13
I've merged @anoff's PR, so I think this can be closed. Any ideas still welcome of course.

**Closed by webpro** 2016-03-23 12:13 UTC
