### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by ivakyb** [webpro/reveal-md#256] opened 2019-06-12 19:50 UTC
reveal-md https://raw.githubusercontent.com/webpro/reveal-md/master/demo/a.md

```
[Error: ENOENT: no such file or directory, stat '/Users/ivakyb/https:/raw.githubusercontent.com/webpro/reveal-md/master/demo/a.md'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/Users/kyb/devel/yocto-presentation/https:/raw.githubusercontent.com/webpro/reveal-md/master/demo/a.md'
}
```

**Comment by ivakyb** [comment] 2019-06-12 19:53
## Workaround
    wget https://raw.githubusercontent.com/webpro/reveal-md/master/demo/a.md
    reveal-md a.md

**Comment by HoverBaum** [comment] 2019-06-13 13:44
A duplicate of #245 which also describes the same error, although doesn't mention the workaround.

Maybe you could open a PR to update the docs @ivakyb, at least until this is fixed 🙂

**Comment by webpro** [comment] 2019-07-06 06:24
I've removed this part from the docs for now. Let's leave this ticket open until it is resolved.

**Closed** 2019-09-11 07:26 UTC
Labels: bug, help wanted, wontfix
